[project]
name = "kneecap-transcribe"
version = "0.0.0"
description = "Transcription Service for Kneecap"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "openai-whisper>=20240930",
    "sqlalchemy>=2.0.40",
]
